name: Janky Thermostat
version: "0.1.8"
slug: janky-thermostat
description: "Home Assistant add-on to control a heater using PID to control a motor to physically articulate the heater knob/valve"
arch:
  - armhf
  - armv7
  - aarch64
init: false

#host_network: true
services:
  - "mqtt:want"

options:
  schedule: [""]
  min_temp: 20.0
  max_temp: 28.0
  posmin: 1034
  posmax: 24600
  posmargin: 50
  speed: 500000
  lograte: 10
  updaterate: 15
  updir: "1"
  i2c_bus: 0
  pigpio_instance: "68413af6-pigpio"
  loglevel: "WARNING"

schema:
  schedule:
    - str
  min_temp: float
  max_temp: float
  posmin: float
  posmax: float
  posmargin: float
  speed: float
  lograte: "int(1,3600)"
  updaterate: "int(1,3600)"
  updir: "list(1|-1)"
  i2c_bus: int
  pigpio_instance: str
  loglevel: "list(CRITICAL|ERROR|WARNING|INFO|DEBUG)"

